# Generated by Django 3.1.6 on 2021-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0005_auto_20210203_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portions', models.IntegerField()),
                ('cooking_time', models.DurationField()),
                ('ingredients', models.ManyToManyField(to='ingredient.Ingredient')),
            ],
        ),
    ]
