# Generated by Django 3.1.6 on 2021-02-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish_chef'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id']},
        ),
    ]
