# Generated by Django 3.1.6 on 2021-02-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210202_0118'),
        ('meal', '0002_auto_20210203_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='category.Category'),
        ),
    ]
