# Generated by Django 3.1.6 on 2021-02-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_auto_20210203_2320'),
        ('meal', '0003_auto_20210203_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='meal',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='dish.Dish'),
        ),
    ]
