# Generated by Django 3.1.6 on 2021-02-03 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chef', '0002_auto_20210201_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cost', models.FloatField(default=0)),
                ('currency', models.CharField(default='BRL', max_length=10, unique=True)),
                ('amount_unit', models.CharField(default='UN', max_length=10, unique=True)),
                ('chef', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='chef.chef')),
            ],
        ),
    ]
