# Generated by Django 3.1.6 on 2021-02-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount_unit',
            field=models.CharField(default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='currency',
            field=models.CharField(default='BRL', max_length=10),
        ),
    ]
