# Generated by Django 3.1.6 on 2021-02-03 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_auto_20210201_2353'),
        ('ingredient', '0004_auto_20210203_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chef.chef'),
        ),
    ]
