# Generated by Django 3.1.5 on 2021-02-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='chef',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
